### ISSUE TITLE
Suggestion for live increasing counter

### ISSUE THREAD

**Issue by murbard** [xtzchad/up.xtzchad.xyz#1]
- Replace the staked amount with a 15 minute exponential moving average of the staked amount. You can do that by polling every block on the backend and updating the EMA.

- When displaying the counter, you know the time since the last block and you know the latest staked amount so you can update the EMA in real time on the client side.

But why? 

The counter will be lagging the real numbers by about 15 minutes, **but** because the changes are smoothed, if you look at the counter it will also always be moving, which is more fun, relaxing and hypnotic.

**Comment by xtzchad** [comment]
There is an initial 1.5 sec animation now, and on first update it'll start continuously moving based on ema calculated from last 60 blocks (15 minutes). Two digits after decimal point were added for better visual effect as int value sometimes moves slow

**Comment by xtzchad** [comment]
5bab234ab24c8bc02a140f907a3884d6487d0042 - Initialize EMA with SMA because it's cool
8e24a8e33c3c3087c1761a0a37a520f53b4c92d5 - latest revision
